version: "3.4"

services:
  hydrography-rest:
    image: sima-hydrography
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      FLASK_ENV: ${FLASK_ENV}
      MONGO_HOST: database
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      INTROSPECTION_URI: http://auth-rest:5000/api/v1/auth/session/introspect
    ports:
      - ${REST_PORT:-5000}:5000
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - sima-network
    entrypoint: ["python", "main.py", "start-flask-server"]

  hydrography-kafka:
    image: sima-hydrography
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      MONGO_HOST: database
      MONGO_PORT: 27017
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      KAFKA_SERVER: kafka:9093
    volumes:
      - .:/app
    depends_on:
      - database
      - kafka
    networks:
      - sima-network
    entrypoint: ["python", "main.py", "start-kafka-consumer"]

  database:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - hydrography-data:/data/db
    networks:
      - sima-network
    command: ["--auth"]
    
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - sima-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 536870912
    networks:
      - sima-network

volumes:
  hydrography-data:
    driver: local

networks:
  sima-network:
    name: sima-network
    driver: bridge
