apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydrography
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydrography-rest
  template:
    metadata:
      labels:
        app: hydrography-rest
    spec:
      containers:
      - name: hydrography-rest
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/hydrography:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-gunicorn-server", "--workers", "12"]
        ports:
        - name: rest
          containerPort: 5000
        envFrom:
          - secretRef:
              name: hydrography-secret
          - configMapRef:
              name: hydrography-conf
        resources:
          limits:
            memory: "512Mi"
            cpu: "150m"
      - name: hydrography-kafka
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/hydrography:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-kafka-consumer"]
        envFrom:
          - secretRef:
              name: hydrography-secret
          - configMapRef:
              name: hydrography-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
